# Uncomment the next line to define a global platform for your project
platform :macos, '10.12'

target 'Simple Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.3'

  # Pods for Simple Login

end
