# Uncomment the next line to define a global platform for your project
platform :macos, '10.12'
use_frameworks!

def common_pods
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyStoreKit'
end

target 'Simple Login' do
  common_pods
end

target 'Safari Extension' do
  common_pods
end
